/*
 * ACL/AscendCL runner skeleton for ComplexGram.
 *
 * This is intentionally a realistic checklist-style host program rather than a
 * fake CPU implementation. Fill in the TODO sections with the kernel launch stubs
 * generated by your msOpGen project.
 */

#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include "../op_kernel/complex_gram_tiling.h"

static std::vector<char> ReadFile(const std::string &path)
{
    std::ifstream ifs(path, std::ios::binary);
    if (!ifs) {
        throw std::runtime_error("failed to open " + path);
    }
    return std::vector<char>((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());
}

static void WriteFile(const std::string &path, const void *data, size_t bytes)
{
    std::ofstream ofs(path, std::ios::binary);
    if (!ofs) {
        throw std::runtime_error("failed to write " + path);
    }
    ofs.write(reinterpret_cast<const char *>(data), static_cast<std::streamsize>(bytes));
}

int main(int argc, char **argv)
{
    if (argc < 4) {
        std::cerr << "Usage: complex_gram_acl_run <n> <input_dir> <output_dir>\n";
        return 1;
    }
    const int32_t n = std::atoi(argv[1]);
    const std::string inputDir = argv[2];
    const std::string outputDir = argv[3];
    const int32_t k = n * 8;
    auto tiling = MakeComplexGramTiling(n, 32, 32, 20, 40);

    std::cout << "ComplexGram ACL runner skeleton\n";
    std::cout << "n=" << n << " K=" << k << " workspace=" << tiling.singleKernelWorkspaceBytes << " bytes\n";

    // Read host input. gen_data.py writes fp16 by default.
    auto ar = ReadFile(inputDir + "/ar.bin");
    auto ai = ReadFile(inputDir + "/ai.bin");
    const size_t bBytes = static_cast<size_t>(17) * k * k * sizeof(float);
    const size_t bsumBytes = static_cast<size_t>(k) * k * sizeof(float);
    const size_t csumBytes = static_cast<size_t>(n) * n * sizeof(float);

    std::vector<float> b(bBytes / sizeof(float), 0.0f);
    std::vector<float> bplur(bBytes / sizeof(float), 0.0f);
    std::vector<float> bplui(bBytes / sizeof(float), 0.0f);
    std::vector<float> bsum(bsumBytes / sizeof(float), 0.0f);
    std::vector<float> csum(csumBytes / sizeof(float), 0.0f);

    // TODO: Replace with real ACL code:
    //   aclInit(nullptr);
    //   aclrtSetDevice(0);
    //   aclrtCreateStream(&stream);
    //   aclrtMalloc(&d_ar, ar.size(), ACL_MEM_MALLOC_HUGE_FIRST);
    //   aclrtMalloc(&d_ai, ai.size(), ACL_MEM_MALLOC_HUGE_FIRST);
    //   aclrtMalloc(&d_workspace, tiling.singleKernelWorkspaceBytes, ACL_MEM_MALLOC_HUGE_FIRST);
    //   aclrtMalloc outputs and tiling buffer;
    //   aclrtMemcpy H2D;
    //   complex_gram_single_do(stream, ...);
    //   complex_gram_reduce_kernel launch on same stream;
    //   aclrtSynchronizeStream(stream);
    //   aclrtMemcpy D2H;
    //
    // Until the generated msOpGen launch stubs are wired, write zero outputs so the
    // file contract can be tested.
    WriteFile(outputDir + "/b.bin", b.data(), bBytes);
    WriteFile(outputDir + "/bplur.bin", bplur.data(), bBytes);
    WriteFile(outputDir + "/bplui.bin", bplui.data(), bBytes);
    WriteFile(outputDir + "/bsum.bin", bsum.data(), bsumBytes);
    WriteFile(outputDir + "/csum.bin", csum.data(), csumBytes);

    std::cout << "Wrote placeholder outputs. Wire ACL launch before numerical verification.\n";
    return 0;
}
