// Official-framework-style host tiling skeleton for ComplexGram.
// Integrate this file into an msOpGen/Ascend custom-op project and replace the
// pseudo registration macros with the exact macros generated by your CANN version.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include "../op_kernel/complex_gram_tiling.h"

struct ComplexGramHostTilingResult {
    ComplexGramTilingData tiling;
    uint32_t cubeBlockDim;
    uint32_t vectorBlockDim;
    uint64_t workspaceBytes;
};

// This function is intentionally framework-independent so it can be unit tested and
// reused inside the real CANN tiling callback.
ComplexGramHostTilingResult BuildComplexGramHostTiling(int32_t n, int32_t bm = 32, int32_t bn = 32)
{
    ComplexGramHostTilingResult r{};
    r.tiling = MakeComplexGramTiling(n, bm, bn, 20, 40);
    r.cubeBlockDim = static_cast<uint32_t>(r.tiling.cubeBlockNum);
    r.vectorBlockDim = static_cast<uint32_t>(r.tiling.vectorBlockNum);
    r.workspaceBytes = r.tiling.workspaceBytes;
    return r;
}

#ifdef COMPLEX_GRAM_TILING_STANDALONE
int main(int argc, char **argv)
{
    const int32_t n = argc > 1 ? std::atoi(argv[1]) : 16;
    const auto r = BuildComplexGramHostTiling(n);
    std::printf("n=%d K=%d BM=%d BN=%d\n", r.tiling.n, r.tiling.k, r.tiling.bm, r.tiling.bn);
    std::printf("tileM=%d tileN=%d tasks=%d\n", r.tiling.tileMNum, r.tiling.tileNNum, r.tiling.taskNum);
    std::printf("cubeBlockDim=%u vectorBlockDim=%u workspace=%llu bytes singleKernelWorkspace=%llu bytes\n",
                r.cubeBlockDim, r.vectorBlockDim,
                static_cast<unsigned long long>(r.workspaceBytes),
                static_cast<unsigned long long>(r.tiling.singleKernelWorkspaceBytes));
    return 0;
}
#endif

/*
Real CANN tiling callback shape, to wire in your generated operator project:

static ge::graphStatus TilingFunc(gert::TilingContext *context) {
    int32_t n = read from attr/input shape;
    auto r = BuildComplexGramHostTiling(n, 32, 32);

    context->SetBlockDim(r.cubeBlockDim);              // for cube kernel
    context->SetTilingKey(...);                        // optional
    context->GetWorkspaceSizes(1)[0] = r.workspaceBytes;

    auto *tiling = context->GetRawTilingData()->GetData<ComplexGramTilingData>();
    *tiling = r.tiling;
    context->GetRawTilingData()->SetDataSize(sizeof(ComplexGramTilingData));
    return ge::GRAPH_SUCCESS;
}

Because this operator launches three kernels, a production package usually exposes a
host launcher that uses the same tiling buffer and launches:
  complex_gram_cube_kernel          with blockDim=20
  complex_gram_vector_epilogue      with blockDim=40
  complex_gram_vector_reduce        with blockDim=40
on the same stream.
*/
