#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
N="${1:-16}"
: "${ASCEND_HOME:=/usr/local/Ascend/ascend-toolkit/latest}"
source "${ASCEND_HOME}/set_env.sh"

PYTHONPATH=. python3 python/gen_data.py --n "${N}" --out "data/n${N}" --dtype float16

# Build custom-op package generated by msOpGen / official sample.
if [ -x ./build.sh ]; then
  ./build.sh
else
  echo "No generated build.sh found. Copy this skeleton into an msOpGen project first." >&2
fi

# Build and run ACL test after wiring real ACL launch stubs.
cmake -S acl_test -B build_acl
cmake --build build_acl -j
mkdir -p "output/n${N}"
./build_acl/complex_gram_acl_run "${N}" "data/n${N}" "output/n${N}"

echo "After wiring real NPU launch, verify with:"
echo "  PYTHONPATH=. python3 python/verify.py --n ${N} --golden data/n${N} --output output/n${N}"
